#
#   Makefile for TVOUT 
#
#   Copyright(c) 2004-2006, Samsung Electronics, Co., Ltd.
#

obj-$(CONFIG_VIDEO_TVOUT)   	:= s3c-tvscaler.o
obj-$(CONFIG_VIDEO_TVOUT)		+= s3c-tvenc.o

EXTRA_CFLAGS += -Idrivers/media/video
