#################################################
# Makefile for Post Processor 
# 2007 (C) Samsung Electronics 
# Author : Jiun. Yu <jiun.yu@samsung.com>
#################################################

s3c_pp-y := s3c_pp_common.o s3c_pp_6400.o

obj-$(CONFIG_VIDEO_PP)		:= s3c_pp.o 
