# S3c64XX Platform Support

obj-$(CONFIG_SND_S3C64XX_SOC) += s3c-pcm.o
obj-$(CONFIG_SND_S5P64XX_SOC) += s3c-pcm.o
obj-$(CONFIG_SND_S5PC1XX_SOC) += s3c-pcm-v50.o
obj-$(CONFIG_SND_S3C_I2S_V32)  += s3c-i2s.o
obj-$(CONFIG_SND_S3C_I2S_V40)  += s3c-i2s.o
obj-$(CONFIG_SND_S3C_I2S_V50)  += s3c-i2s-v50.o
obj-$(CONFIG_SND_S3C_AC97)     += s3c-ac97.o

# S3C24XX Machine Support
snd-soc-neo1973-wm8753-objs := neo1973_wm8753.o
snd-soc-smdk64xx-wm9713-objs := smdk64xx_wm9713.o
snd-soc-smdk6410-wm8580-objs := smdk6410_wm8580.o
snd-soc-smdk6440-wm8580-objs := smdk6440_wm8580.o
snd-soc-smdk6410-wm8990-objs := smdk6410_wm8990.o
snd-soc-smdk6410-wm8993-objs := smdk6410_wm8993.o
snd-soc-smdk6410-s5m8751-objs := smdk6410_s5m8751.o
snd-soc-meizum8-wm8753-objs := meizum8_wm8753.o
snd-soc-smdk6410-wm8753-master-objs := smdk6410_wm8753_master.o
snd-soc-smdk6410-wm8753-slave-objs := smdk6410_wm8753_slave.o

obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM9713) += snd-soc-smdk64xx-wm9713.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8580) += snd-soc-smdk6410-wm8580.o
obj-$(CONFIG_SND_S5P64XX_SOC_SMDK6440_WM8580) += snd-soc-smdk6440-wm8580.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8990) += snd-soc-smdk6410-wm8990.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8993) += snd-soc-smdk6410-wm8993.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_S5M8751) += snd-soc-smdk6410-s5m8751.o
obj-$(CONFIG_SND_S3C64XX_SOC_MEIZUM8_WM8753) += snd-soc-meizum8-wm8753.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8753_MASTER) += snd-soc-smdk6410-wm8753-master.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8753_SLAVE) += snd-soc-smdk6410-wm8753-slave.o
