#################################################
# Makefile for Post Processor 
# 2007 (C) Samsung Electronics 
# Author : Jiun. Yu <jiun.yu@samsung.com>
#################################################

s3c_camera-y := s3c_camera_driver.o s3c_camif.o s5k4ba.o

obj-$(CONFIG_VIDEO_CAM)		:= s3c_camera.o 
