obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
obj-$(CONFIG_VIDEO_CAM)		+= camera/
obj-$(CONFIG_VIDEO_G2D)		+= g2d/
obj-$(CONFIG_VIDEO_G3D)		+= g3d/
obj-$(CONFIG_VIDEO_MFC)		+= mfc/
obj-$(CONFIG_VIDEO_PP)		+= pp/
obj-$(CONFIG_VIDEO_ROTATOR)	+= rotator/
obj-$(CONFIG_VIDEO_JPEG)	+= jpeg/
obj-$(CONFIG_VIDEO_TVOUT)	+= tvout/
obj-$(CONFIG_VIDEO_CMM)		+= cmm/


EXTRA_CFLAGS += -Idrivers/media/video

