#################################################
# Makefile for CMM on S3C6410
# 2008 (C) Samsung Electronics
# Author : joghun.han <jonghun.han@samsung.com>
#################################################

s3c_cmm-y 	:= LogMsg.o CMMMisc.o s3c-cmm.o 

obj-$(CONFIG_VIDEO_CMM)		:= s3c_cmm.o
