#################################################
# Makefile for Rotator on S3C6410
# 2008 (C) Samsung Electronics
# Author : jh.han <jonghun.han@samsung.com>
#################################################

#s3c_rotator-y := LogMsg.o JPGOpr.o JPGMisc.o JPGMem.o s3c-jpeg.o

obj-$(CONFIG_VIDEO_ROTATOR)		:= s3c_rotator.o 
