#################################################
# Makefile for JPEG Driver
# 2007 (C) Samsung Electronics 
# Author : Jiun. Yu <jiun.yu@samsung.com>
#################################################

s3c_jpeg-y := LogMsg.o JPGOpr.o JPGMisc.o JPGMem.o s3c-jpeg.o

obj-$(CONFIG_VIDEO_JPEG)		:= s3c_jpeg.o 



